### ISSUE TITLE
I met this surf license error when run 

### ISSUE THREAD

**Issue by bemoregt** [kushalvyas/Python-Multiple-Image-Stitching#7]
HI, @kushalvyas , @Nourahussein 

I met this error when run 

kerb:code mun$ 
kerb:code mun$ python3 pano.py files.txt 
Parameters :  files.txt
['../../images/1.png', '../../images/2.png', '../../images/3.png', '../../images/4.png', '../../images/5.png']
Traceback (most recent call last):
  File "pano.py", line 138, in <module>
    s = Stitch(args)
  File "pano.py", line 16, in __init__
    self.matcher_obj = matchers()
  File "/Users/mun/Python-Multiple-Image-Stitching/code/matchers.py", line 6, in __init__
    self.surf = cv2.xfeatures2d.SURF_create()
cv2.error: OpenCV(3.4.3) /Users/travis/build/skvark/opencv-python/opencv_contrib/modules/xfeatures2d/src/surf.cpp:1016: error: (-213:The function/feature is not implemented) This algorithm is patented and is excluded in this configuration; Set OPENCV_ENABLE_NONFREE CMake option and rebuild the library in function 'create'

What's wrong with me?

my Env: MacOSX Mojave, Python3.7, OpenCV3.x

from @bemoregt

**Comment by kushalvyas** [comment]
you need opencv contrib . SIFT/ SURF are a part of opencv contrib now.  I think this will help : https://www.pyimagesearch.com/2015/07/16/where-did-sift-and-surf-go-in-opencv-3/
